# -*- coding: utf-8 -*-
"""Exercice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaTMEFhICRXZYIC4dTtFLgv25WmopP9D
"""

import pandas as pd

"""## Exercice 1

**1.Qu'est ce que l'analyse de données**

L'analyse de données est un processus d' inspection , de nettoyage , de transformation et de modélisation des données visant à en extraire des informations utiles, à éclairer les conclusions et à faciliter la prise de décision

**2.Pourquoi l'analyse des données est-elle importante ?**

Dans les contextes modernes, l'analyse de données est devenue indispensable pour plusieurs raisons :

- Prise de décision éclairée : Les organisations s'appuient sur des données concrètes plutôt que sur l'intuition, réduisant les risques d'erreur.
- Compétitivité : Les entreprises qui exploitent leurs données prennent de l'avance en identifiant les tendances du marché avant leurs concurrents.
- Optimisation des processus : L'analyse permet de détecter les inefficacités et d'améliorer les opérations.
Personnalisation : Les services peuvent être adaptés aux besoins spécifiques des utilisateurs grâce à la compréhension de leurs comportements.

**3.Trois domaines d'application actuels de l'analyse de données**
- Santé
- Marketing
- Climat

## Exercice 2
"""

def charger_dataset(chemin_fichier, n_lignes=5):

    try:
        if chemin_fichier.endswith('.csv'):
            df = pd.read_csv(chemin_fichier)

        elif chemin_fichier.endswith(('.xlsx', '.xls')):
            df = pd.read_excel(chemin_fichier)

        else:
            print("Unsupported file format.")
            return

        print("\n=== First lines of the dataset ===")
        print(df.head(n_lignes))


        print("\n=== General Information ===")
        print(f"Number of rows : {df.shape[0]}")
        print(f"Number of columns : {df.shape[1]}")

        print("\n=== Column types ===")
        print(df.dtypes)

        print("\n=== Missing Values ===")
        print(df.isnull().sum())

        print("\n=== Statistical Description ===")
        print(df.describe(include='all'))

        return df

    except FileNotFoundError:
        print("Not Found file.")

    except Exception as e:
        print(f"Erreur : {e}")

# Exemple d'utilisation
chemin = 'C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\Mental health Depression disorder Data.csv'
chemin1 = 'C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\clean_dataset.csv'
chemin2 = 'C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\crx.csv'
chemin3 = 'C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\Time Americans Spend Sleeping.csv'
dk = charger_dataset(chemin)
# dg = charger_dataset(chemin1)
# dh = charger_dataset(chemin2)
# di = charger_dataset(chemin3)

"""## Exercice 3"""



"""## Exercice 4"""

iris_data = pd.read_csv('C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\iris.csv')
iris_data

iris_data.select_dtypes('number').columns
print(iris_data.to_string(index=False))
iris_data.describe()

"""## Exercice 5"""

time_data = pd.read_csv('C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\Time Americans Spend Sleeping.csv')
print('=== DataFrame créé ===')

time_data.head()
time_data.describe()
time_data.info()
time_data.groupby('Sex')['Year'].mean()

"""## Exercice 6"""

structured_analysis = {
    'Source de données': [
        '1. Rapports financiers dans un fichier Excel',
        '2. Photographies sur une plateforme de médias sociaux',
        '3. Collection d\'articles de presse sur un site web',
        '4. Données d\'inventaire dans une base de données relationnelle',
        '5. Enregistrements d\'entretiens issus d\'une étude de marché'
    ],
    'Type': [
        'STRUCTURÉES',
        'NON STRUCTURÉES',
        'NON STRUCTURÉES',
        'STRUCTURÉES',
        'NON STRUCTURÉES'
    ],
    'Justification': [
        'Organisation en lignes/colonnes avec schéma défini. Chaque cellule a un type et une position fixes.',
        'Format image (pixels) sans schéma tabulaire. Le contenu visuel ne suit pas une organisation en colonnes.',
        'Texte libre avec mise en forme HTML variable. Pas de schéma rigide — longueur, style et structure varient.',
        'Stockage selon un schéma fixe avec types de données définis, clés primaires et relations entre tables.',
        'Audio non indexé. Le contenu verbal est continu et non organisé en champs de données définis.'
    ]
}

df_structured = pd.DataFrame(structured_analysis)
print('=== Exercice 6 : Données Structurées vs Non Structurées ===')
for _, row in df_structured.iterrows():
    print(f"\n{row['Source de données']}")
    print(f"  → {row['Type']}")
    print(f"    → {row['Justification']}")

"""## Exercice 7"""

sleep_types = {
    'Colonne': ['Age', 'Gender', 'Sleep Duration (hours)', 'Work Hours Per Week',
                'Stress Level', 'Sleep Quality', 'BMI Category', 'Physical Activity (min/day)'],
    'Type': ['Quantitative', 'Qualitative', 'Quantitative', 'Quantitative',
             'Qualitative', 'Qualitative', 'Qualitative', 'Quantitative'],
    'Justification': [
        'Valeur numérique mesurable (années)',
        'Catégorie nominale (Male/Female) — pas de hiérarchie naturelle',
        'Valeur numérique continue (heures de sommeil)',
        'Valeur numérique discrète (heures travaillées)',
        'Catégorie ordinale (Low/Medium/High) — hiérarchie mais pas d\'intervalle fixe',
        'Catégorie ordinale (Poor/Fair/Good/Excellent)',
        'Catégorie nominale (Normal/Overweight/Obese)',
        'Valeur numérique continue (minutes par jour)'
    ]
}

df_types_sleep = pd.DataFrame(sleep_types)
print('Catégorisation des colonnes — Dataset Sommeil ===')
print(df_types_sleep.to_string(index=False))

credit_types = {
    'Colonne': ['Age', 'Income (USD)', 'Credit Score', 'Employment Status',
                'Years Employed', 'Debt (USD)', 'Prior Defaults', 'Approval'],
    'Type': ['Quantitative', 'Quantitative', 'Quantitative', 'Qualitative',
             'Quantitative', 'Quantitative', 'Qualitative', 'Qualitative'],
    'Justification': [
        'Valeur numérique (années)',
        'Valeur numérique continue (dollars)',
        'Score numérique sur une échelle définie (300-850)',
        'Catégorie nominale (Employed/Self-Employed/Part-Time/Unemployed)',
        'Valeur numérique discrète (nombre d\'années)',
        'Valeur numérique continue (dollars de dette)',
        'Catégorie binaire (Yes/No)',
        'Catégorie binaire nominale (Approved/Rejected)'
    ]
}

df_types_credit = pd.DataFrame(credit_types)
print('=== Catégorisation des colonnes — Dataset Crédit ===')
print(df_types_credit.to_string(index=False))

"""## Exercice 8"""

train_data = pd.read_csv('C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\train.csv')
train_data.head()

"""## Exercice 9"""

# Création d'un DataFrame simple

import pandas as pd
data_exemple = {
    'Produit': ['Ordinateur', 'Smartphone', 'Tablette', 'Écouteurs', 'Montre connectée'],
    'Catégorie': ['Informatique', 'Téléphonie', 'Informatique', 'Audio', 'Accessoires'],
    'Prix (€)': [899.99, 699.00, 349.50, 149.99, 249.00],
    'Stock': [45, 120, 30, 200, 75],
    'Note client': [4.5, 4.7, 4.2, 4.8, 4.3]
}

df_produits = pd.DataFrame(data_exemple)
print('=== DataFrame créé ===')
print(df_produits)
df_produits.to_csv('produits.csv', index=False)
df_produits.to_json('produits.json', orient='records')

"""## Exercice 10"""

posts_data = pd.read_json('C:\\Users\\meles\\Documents\\TTA_DI_BootCamp_Gilles-Chris_MAKE\\posts.json', orient='records')
posts_data.head()

cols_simples = ['body', 'title']

posts_data[cols_simples].head()